// demo/src/components/GraphView.tsx
import React, { useRef, useEffect } from 'react';
import { NoteGraphView, GraphViewOptions, NoteGraphModel } from '../note-graph'

interface Props {
  graphModel: NoteGraphModel
  graphViewOptions?: Omit<GraphViewOptions, 'container'>
}

const GraphView = (props: Props) => {
  const graphViewWrap = useRef(null)

  useEffect(() => {
    const view = new NoteGraphView({
      container: graphViewWrap.current,
      ...props.graphViewOptions || {},
    })
    view.updateViewData(props.graphModel.toGraphViewData())
    view.initView()
    return () => {
    };
  });

  return (
    <div ref={graphViewWrap} className="graph-view">
    </div>
  );
}

export default GraphView;

// demo/src/components/GraphView.vue
<template>
<div class="graph-view-wrap" ref="graphViewWrap"></div>
</template>

<script lang="ts">
import { defineComponent, onMounted, ref } from 'vue';
import { NoteGraphView, GraphViewOptions, NoteGraphModel } from '../note-graph'

export default defineComponent({
  name: 'GraphView',
  props: {
    graphModel: {
      type: Object as () => NoteGraphModel,
      required: true,
    },
    graphViewOptions: Object as () => GraphViewOptions,
  },
  setup(props) {
    const graphViewWrap = ref(null)
    function initGraphView() {
      const view = new NoteGraphView({
        container: graphViewWrap.value,
        ...props.graphViewOptions || {},
      })
      view.updateViewData(props.graphModel.toGraphViewData())
      view.initView()
    }

    onMounted(() => {
      initGraphView()
    })

    return {
      graphViewWrap,
    }
  },
})
</script>
